
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

int FUN_ram_42023318(void)

{
  char *pcVar1;
  int iVar2;
  
  iVar2 = 0x103;
  if (_DAT_ram_3fcc5188 != 0) {
    pcVar1 = 
    "ANgZABdgMgDYDAMMDGDQAFgxgYcPAH0A9gAPDwwMYPAAcDHDBw8AOHBkAOcD/gwMYHAAcDD+BwYAH+EA9gAA8AQEQGAAIDA4AgYAB4AyAAECAAVfAQcsAQECAAi/BwTbAV8AAAAAAxkABgIgAAICAAgyAAkCAA8ZACYIdwACXAIDSwAYw2AACBkAHwMZAB70Ak/B4E4eA8AI4A8GYA8weCAQsQj0As/H8P8/D+Af+D+H4D+w/jAwGQD3AMMOGOHjnDAOHHHHADDxhxkA9QEMHOHBmDAMDGDGAGBxAxhgMgDYDAzAwZwADAzAZgBgcBkA5x/8wIGPAAwO/+YAYDAfMgD1AR/8wIGH4AgG/+YAYDH/DMBLAOcYAMCBgPAMDsAGAGAzgxkA6AwAwIGAMAwMwAYAYHMDGQAxDMCBlgB1ZgBgcwcHgEsA9QEOGMCBnDAOHHDGADDzjweGGQD0Acf4wcGP4Av4P4YAP7H7Aw4ZAPQCQcHgQIEDwAjgDgYADiDzAwQZAAN2ARMICAAVA6kBAxEABBkAHAYZABMcIQAcHhkABDIAByADDQIAAw0CDRgAC5YABwIADzIA//////8LCBMIBAIAAdIPDwQQBQ82EAYPaBAGD5oQBg/MEAYPmRABAf4QDzARBg/kEAEBYhEPlBEGD8YRBg/4EQYPAgCvUAAAAAAA"
    ;
    DAT_ram_3fcc517e = 0;
    do {
      iVar2 = FUN_ram_42066872(_DAT_ram_3fcc5188,pcVar1);
      if (iVar2 != 0) {
        return iVar2;
      }
      pcVar1 = pcVar1 + 0x10;
      iVar2 = 0;
    } while (pcVar1 != 
             "YHAAcDD+BwYAH+EA9gAA8AQEQGAAIDA4AgYAB4AyAAECAAVfAQcsAQECAAi/BwTbAV8AAAAAAxkABgIgAAICAAgyAAkCAA8ZACYIdwACXAIDSwAYw2AACBkAHwMZAB70Ak/B4E4eA8AI4A8GYA8weCAQsQj0As/H8P8/D+Af+D+H4D+w/jAwGQD3AMMOGOHjnDAOHHHHADDxhxkA9QEMHOHBmDAMDGDGAGBxAxhgMgDYDAzAwZwADAzAZgBgcBkA5x/8wIGPAAwO/+YAYDAfMgD1AR/8wIGH4AgG/+YAYDH/DMBLAOcYAMCBgPAMDsAGAGAzgxkA6AwAwIGAMAwMwAYAYHMDGQAxDMCBlgB1ZgBgcwcHgEsA9QEOGMCBnDAOHHDGADDzjweGGQD0Acf4wcGP4Av4P4YAP7H7Aw4ZAPQCQcHgQIEDwAjgDgYADiDzAwQZAAN2ARMICAAVA6kBAxEABBkAHAYZABMcIQAcHhkABDIAByADDQIAAw0CDRgAC5YABwIADzIA//////8LCBMIBAIAAdIPDwQQBQ82EAYPaBAGD5oQBg/MEAYPmRABAf4QDzARBg/kEAEBYhEPlBEGD8YRBg/4EQYPAgCvUAAAAAAA"
            );
  }
  return iVar2;
}

