
char FUN_ram_4201c1f0(uint param_1)

{
  int in_a4;
  ushort *in_a5;
  
  do {
    if (*in_a5 == param_1) {
      return "HwABAP+ZPBIPoK4BSxft//wUAFsB7Vt//hQAWwy27b//FABpZ6+////QFQB5AZq69X//6BQAagxt5Cx//z0AiCGjQNj//3/wKQB4RocS9X//pykAlwGPHf+///8xXykAlwYYNqaB//946qMAtQg4eg8B///+fQ/AUgC1EODBFAP//q/ugfgUALVhwcCcB///D/+gPhQAtIMDQHgF//4FH/AHPQDEAQcGIGgH//8GBP4BegDTAhwOIPAP//8DA3/gPD0A0wQYGBXEHf/+A4MT+A8UANMIMDgBwRf//wKBmB+BUQDiEHAwB4Af//8BwMyD4OApAOIg4GADgDv//QHAxkB8OBQA4kHAwAd3////AUBDIA+MFADiQ4HAD73v//8A4GMgA2YUAOGDAYA+gn////DAMZAAuxQA8AEBBgMA3ABr////4DDIAB2AlgPxAAIOBgE8AP//+w/+GMQABygA8QACHAYCtADX//8Af/hkAAGhAPIVBBgMAjgA9//2gHH+YgAAcAAAAAAIMAwBcAHv//cAcB/xAAEoFADRGAJwAc///wBwBv8ABKEA8AEQYDgA4AHv/+cAUAwfwCIGDgTxASBgMADgA8//7QAwBhn9CAIUAPAAwGAB4APP/+8AeAYMf4ABNgTxACHAYAHAA5//7wAwAwwn4BQA8QBBgMAB1Aef/+cAOAMGIHw8AJFBgMADgAef/88UACAfBHIE8QCDAMADggcf/84AOAMGEAOmAfIVgwGAA4CPH//PADgBgxAA+AAAAAEDAYAHAC8//84AOAGDCSQfKwFSgAcADz8oAEGMAAWAFADyKAAPAA4//54AOAGBCAAB4AAAAg4DAA4AHj//jgA4AYGEAAB4AAACDAYADgAef/+eADgAwYQAAAwUAGMMAB4//5YUAKIHAAAEDAYAHgA6KADzFsDCAAACgAAEGAYAHAAcf/8eACgAwMIAAADAAAQYDAAcADx//x4oACEAYBQAZDgAPH//HBQA8w4wAAgYDAA4AHj//z4AOADAwQAAABAACDAMADgAOCgAkUEAAAAIAAgwGCgAc/48ADgAwOEoADUYAHAUAAYoAPEAcABw//40ADgAwGEAAAAgPACCcAD5//48AHA8ABOgFAAx8f/8UADxFWEAAAQAAAhgMABwAPH//ngAcADAYQABIQAAEDAYAOAA4f/8ODwAMgRIACgAUeAB8f/8KAARQJMCMhBgMCgAARQAEWGTApEIYDAA4AHj//gUABLgKAASIBQAIvzwZAABfwIBKACGw//4cADgAYBQAILAAeP/+PAAYLQAAVAAxQHgA8f/+PAA4AGAQWQAUcADx//wFAASwRQAlyBwAcADx//54BQAIXAgFAA28OABFAC2IDABwANH//HgAMAoAMQwAcADz//x4AHAAwBQANEwAcAHh//hwAHAAwGCZACcBDAwAcADj//zFAB1B4//48ADgCgANDFyAxQAFAY8ANM0MAGAB5//44ADgAYDUACBODABwAcf/8cUAAEKA9UAAjAwAcAHn//HgAcAFABhmBgBwA8fFAAUDCgAEpg8AGLPAAcADAYUAPEAARgYAcAPP//NAA4ADAYItAAiAYwUAGfPAA4AGA4UAJILP/+PAB4AGAwUADEAzAg8AHGeABwAOAwQPAAyAOYcFABTIBwAMBgUAOJWDAHADX//mgQ4ADAYICgAYd4MAcAPf88CImA4FADxCCovDAFADn//nAF4AGAwQAAAAAABQCcGKAABVwIRYBQA8AECABHGAOANf/98AHAAwGCAgAjxAAQAEeYBwA7//zgA5AGAwBQAkQIACPsA4A9//i8CEcF3APEABAAI3wDgHf//eAHCAwGDFADTAwAEZYBgDv/+8AHBB2cB0wIABEHw4A///uADQIY/AfEAAcACMf5wG///sAOAjAYMPADTAEABOM/QD//+4AcAjCsB4wB4AJhB8A3//8AHAJgMAwHEFACMYH8f//7QDgE4AwHiDwBKYD/3///AHAawOGBQANEDwCYwMP///oEcFOBwxwDTAAAA8BMYGA//..." /* TRUNCATED STRING LITERAL */
             [in_a4 + 0x81c];
    }
    in_a4 = in_a4 + 1;
    in_a5 = in_a5 + 1;
  } while (in_a4 != 0x1c);
  return '\0';
}

