
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_ram_4201a074(void)

{
  int iVar1;
  int iVar2;
  char *pcVar3;
  undefined4 uVar4;
  undefined1 auStack_14 [12];
  
  iVar1 = FUN_ram_4201f03c();
  if (iVar1 != 0) {
    FUN_ram_42018dcc();
    return;
  }
  iVar1 = FUN_ram_4201ee6a();
  if (iVar1 != 0) {
    iVar2 = FUN_ram_4201605e();
    if (_DAT_ram_3fcc504c == 0) {
      if (iVar2 == 0) {
        pcVar3 = 
        "AXsFEh9DACIAABMGEj+BBTEAAH8YAAQJBkgAP///NwYRDw8AA6QAAoAGI///hgAxAAAAHgABCgABAgAZBx0ADwIAEVAAAAAAAA=="
        ;
        uVar4 = 0x744;
      }
      else {
        pcVar3 = 
        "x+PMBkAAAADDDwA15EAADwDCAAIn4kgCQAAAAOcASwCS4k/+QAAAA//gaQCS4kgDQAAAB/3khwCT48AAYAAAP4D8pQCCQAAgAAA/AP7DABFyDwAxPgA+DwAC/wAiAHwPABUEDwAhOwAdAQE7AQK0AYIIAAeOcSAAkA4AAVkBN3kgAQ8AU545EAfIHgCDEAAInDiQDggPAIMSAAmcOJA4ZA8AhCcACRw8yuHkDwBzgBM8HInHkg8AhEDgETgcSQ4SDwBzOBI4HkQ4eQ8AgoAPIngOJOHgZwKhAZwDJHAOOkeAwB8AgQMPwlxwDyJOPAHBAAACBP5E8AcROA4gHgCSBAIciOAHmTB80wCSCAEEmeADj5OYpgChEACB8cADx4wwBC0AoSAAQePAAcZIcAMPAPIKwAAyY4AB4iDgAYAAAAABgAAkR4AA8iHACGYD8ZcABE8AAPFzgA4wAAAADAAADo8AAHiJABkcAAAAOAAAER4AADzEABnHAAAA4gAAIzwAADxGADMA4AAHAwAAYjwAAB4mACMIPgB8AYAAZHgAAA8ZAGYYAf+AAcAAmPAAAAeIgMw4AAAAAWABEeAAAAfEQMxQAcQAATACI+AAAAPCc5iQAYQAAJgOQ8AAAAHhmZGwAYQAAI4Zh4AAAADwhHMwAY4AAIYhQQOweEYWMAGOAACEYh74BaE8JYwgAYoAAEGk+wTxCh8YQGABiwAAwhj4AAAAAA+EcOABkwAADiHPBaEHw2wgAZEAADbDRgWiA+HjAAGRgADHh38Bg/hh4AGhgAeG3QWRfho4A7HAHFh+QgGiAD8GD4AAAfBg/A8AgQ/B0HwAPguDWQChAAAH8DBD/8IMD1kAQQAAAfwnBhI/5wF2AAB/gPoYf3MGYR/wAf+AD6MAAT0AU/4AAAB/OwB3AAAA//gAH74GRR////8sAFkAAAH//+sGkAf/4AAAAAAAAA=="
        ;
        uVar4 = 0x580;
      }
      iVar1 = FUN_ram_42021020(pcVar3,uVar4,iVar1,auStack_14);
      if (iVar1 != 0) {
        FUN_ram_4201eeb2(0);
      }
    }
    else {
      if ((_DAT_ram_3fcc504c & 0xfffffffd) != 1) {
        if (_DAT_ram_3fcc504c != 2) {
          return;
        }
        iVar1 = FUN_ram_42021020("4iAAAMAAAAADAAGEZwABxkAAAQDmAaGAAwJjgAGPyAAGNAGhYAYD8YADi5gADA8AkTAcGdHAAxEEAKQAsQAYeDyIwAcRBAAwHgChCPDkiOAHInoAYA8AoQNjhkTgDjp//EAPAJEezw5ccA5kAfx+AaEA8Jw4JnAcRACJHQCiAMEQ4CIwHEwAQw8AksNDwBI4HIgAUjwAkYZPABE4GMgAJGkAoQGEJAATGDiQACToAaEP/CQACRw5EAAI6AHz0Q+YEAAInDkQAAgH+8AAAB8AEAAInHEwABgDPuAAAD8AGAAEjnEgABABjGAAAHwACAAEjnHgABAAjGAAAPAACAAHjnIgACAA1kAAA+AABAAETnIgACAA/zAAB8AABAAETmJAACAAY+AAH4AABAACRuJAACAAYTAAfwAABAACR+PAAWAAZZgB/gAABgADx+JIB0AAf+cB/AAAAsASR+JOHkAAPJmB+AAAAn/yR+ZB+EAAAAj/8AAAAkASJ+ZD4EAAAA//8AAAAgACJ+PPGEAAAAfnAAAAAn/zx+PMBkAAAADDDwA15EAADwDCAAIn4kgCQAAAAOcASwCS4k/+QAAAA//gaQCS4kgDQAAAB/3khwCT48AAYAAAP4D8pQCCQAAgAAA/AP7DABFyDwAxPgA+DwAC/wAiAHwPABUEDwAhOwAdAQE7AQK0AYIIAAeOcSAAkA4AAVkBN3kgAQ8AU545EAfIHgCDEAAInDiQDggPAIMSAAmcOJA4ZA8AhCcACRw8yuHkDwBzgBM8HInHkg8AhEDgETgcSQ4SDwBzOBI4HkQ4eQ8AgoAPIngOJOHgZwKhAZwDJHAOOkeAwB8AgQMPwlxwDyJOPAHBAAACBP5E8AcROA4gHgCSBAIciOAHmTB80wCSCAEEmeADj5OYpgChEACB8cADx4wwBC0AoSAAQePAAcZIcAMPAPIKwAAyY4AB4iDgAYAAAAABgAAkR4AA8iHACGYD8ZcABE8AAPFzgA4wAAAADAAADo8AAHiJABkcAAAAOAAAER4AADzEABnHAAAA4gAAIzwAADxGADMA4AAHAwAAYjwAAB4mACMIPgB8AYAAZHgAAA8ZAGYYAf+AAcAAmPAAAAeIgMw4AAAAAWABEeAAAAfEQMxQAcQAATACI+AAAAPCc5iQAYQAAJgOQ8AAAAHhmZGwAYQAAI4Zh4AAAADwhHMwAY4AAIYhQQOweEYWMAGOAACEYh74BaE8JYwgAYoAAEGk+wTxCh8YQGABiwAAwhj4AAAAAA+EcOABkwAADiHPBaEHw2wgAZEAADbDRgWiA+HjAAGRgADHh38Bg/hh4AGhgAeG3QWRfho4A7HAHFh+QgGiAD8GD4AAAfBg/A8AgQ/B0HwAPguDWQChAAAH8DBD/8IMD1kAQQAAAfwnBhI/5wF2AAB/gPoYf3MGYR/wAf+AD6MAAT0AU/4AAAB/OwB3AAAA//gAH74GRR////8sAFkAAAH//+sGkAf/4AAAAAAAAA=="
                                 ,0x218,iVar1,auStack_14);
        if (iVar1 != 0) {
          FUN_ram_4201eeb2(0);
        }
        FUN_ram_42019edc();
        FUN_ram_42019e8c();
        FUN_ram_4201f108(0x12,0xb6);
        _DAT_ram_3fcc5044 = _DAT_ram_3fcc5044 + 1;
        if (_DAT_ram_3fcc5044 < 3) {
          FUN_ram_42019c6c();
          FUN_ram_42018dcc();
          return;
        }
        _DAT_ram_3fcc504c = 3;
        return;
      }
      iVar1 = FUN_ram_42021020("4iAAAMAAAAADAAGEZwABxkAAAQDmAaGAAwJjgAGPyAAGNAGhYAYD8YADi5gADA8AkTAcGdHAAxEEAKQAsQAYeDyIwAcRBAAwHgChCPDkiOAHInoAYA8AoQNjhkTgDjp//EAPAJEezw5ccA5kAfx+AaEA8Jw4JnAcRACJHQCiAMEQ4CIwHEwAQw8AksNDwBI4HIgAUjwAkYZPABE4GMgAJGkAoQGEJAATGDiQACToAaEP/CQACRw5EAAI6AHz0Q+YEAAInDkQAAgH+8AAAB8AEAAInHEwABgDPuAAAD8AGAAEjnEgABABjGAAAHwACAAEjnHgABAAjGAAAPAACAAHjnIgACAA1kAAA+AABAAETnIgACAA/zAAB8AABAAETmJAACAAY+AAH4AABAACRuJAACAAYTAAfwAABAACR+PAAWAAZZgB/gAABgADx+JIB0AAf+cB/AAAAsASR+JOHkAAPJmB+AAAAn/yR+ZB+EAAAAj/8AAAAkASJ+ZD4EAAAA//8AAAAgACJ+PPGEAAAAfnAAAAAn/zx+PMBkAAAADDDwA15EAADwDCAAIn4kgCQAAAAOcASwCS4k/+QAAAA//gaQCS4kgDQAAAB/3khwCT48AAYAAAP4D8pQCCQAAgAAA/AP7DABFyDwAxPgA+DwAC/wAiAHwPABUEDwAhOwAdAQE7AQK0AYIIAAeOcSAAkA4AAVkBN3kgAQ8AU545EAfIHgCDEAAInDiQDggPAIMSAAmcOJA4ZA8AhCcACRw8yuHkDwBzgBM8HInHkg8AhEDgETgcSQ4SDwBzOBI4HkQ4eQ8AgoAPIngOJOHgZwKhAZwDJHAOOkeAwB8AgQMPwlxwDyJOPAHBAAACBP5E8AcROA4gHgCSBAIciOAHmTB80wCSCAEEmeADj5OYpgChEACB8cADx4wwBC0AoSAAQePAAcZIcAMPAPIKwAAyY4AB4iDgAYAAAAABgAAkR4AA8iHACGYD8ZcABE8AAPFzgA4wAAAADAAADo8AAHiJABkcAAAAOAAAER4AADzEABnHAAAA4gAAIzwAADxGADMA4AAHAwAAYjwAAB4mACMIPgB8AYAAZHgAAA8ZAGYYAf+AAcAAmPAAAAeIgMw4AAAAAWABEeAAAAfEQMxQAcQAATACI+AAAAPCc5iQAYQAAJgOQ8AAAAHhmZGwAYQAAI4Zh4AAAADwhHMwAY4AAIYhQQOweEYWMAGOAACEYh74BaE8JYwgAYoAAEGk+wTxCh8YQGABiwAAwhj4AAAAAA+EcOABkwAADiHPBaEHw2wgAZEAADbDRgWiA+HjAAGRgADHh38Bg/hh4AGhgAeG3QWRfho4A7HAHFh+QgGiAD8GD4AAAfBg/A8AgQ/B0HwAPguDWQChAAAH8DBD/8IMD1kAQQAAAfwnBhI/5wF2AAB/gPoYf3MGYR/wAf+AD6MAAT0AU/4AAAB/OwB3AAAA//gAH74GRR////8sAFkAAAH//+sGkAf/4AAAAAAAAA=="
                               ,0x218,iVar1,auStack_14);
      if (iVar1 != 0) {
        FUN_ram_4201eeb2(0);
      }
      FUN_ram_42019edc();
    }
    FUN_ram_42019e8c();
    if (*(char *)(gp + -0x794) == '\0') {
      FUN_ram_4201f108(0,199);
    }
    else {
      FUN_ram_4201ef22();
      *(undefined1 *)(gp + -0x794) = 0;
    }
  }
  return;
}

