
void FUN_ram_4201ac5a(undefined1 param_1)

{
  uint uVar1;
  int iVar2;
  undefined4 uVar3;
  
  *(undefined1 *)(gp + -0x791) = param_1;
  uVar1 = FUN_ram_4201666a();
  DAT_ram_3fcc5094 = (undefined1)uVar1;
  if (uVar1 < 7) {
    if ("HwABAJ0vP/8BAABPAAAAARcAAG///8AAAAcZAAJP8AAADxkAAk/4AAAfGQACH/x8AARv//4AAD/gRwEAbwH+AAB/gBkAAF8A/wAAf34AAV/4fwAA/uEAAW/+P4AA/HBLAABvBz+AAPxgGQAAoQOfgAD8x/////wZAQaHAKEBn4AA/N/////+GQEVwDwADxkAPW/P/////AN9AAAGcwAGAgABfQAPGQD/////DiIB/C4EMmDADAkABDMEEwHcBA8ZAAYUAFgEBTIA2YH4fMN8HgHj8Dw+AfAZAMjMxsN2MwBgwAxjAxgZAMn5hsDDY2GAYMAMYAAZAFGBhnDDYBkAODgA+DIA2oGGHMNgfwBgwAwOAbgZAJoGw2BgAGDADANkANiBhsZnYDGAeMAPYwM4MgDI/YZ8P2AfADBwBj4BZAANAgAE4QANAgAPGQD/VlDAAAAAA1MJCiYCDxkAIMl4wPD4eD8AHj8H48H0AcnMwZmMzGcAMzmM5mMmAsmGww2BhsMAYbDYbDajAn+AwwzhhsM+GQACnDn8wwB/MNhv5jIAmA2AwwBgMNhsBhkA2ADG2ZmMxmcAMbDM5jN9ANkAfHDw+Hw/AB8wx+PhrwAMAgAPigL/VgsCAAt3ARUwMwoPGQAWBVEABjIAkgH7DHh8/eDx+BwABhkAnAM7DMzGMGGZzBkAnwYbDYbAMGMNhhkAAR9wGQAEL/wcGQAEL4AGGQABoQM5nMbGMHmZhjhlAAaWAI0B+Px8fBww8RkAAdIFBgIABjIADxkAIAoCAAdLAAoCAA8ZAP//GxE+OwLDYAAKcACACAABEAAEPwIRIBkATCAACiAZAPIcZQGRM04jEAAjgeY5kQPcYBzIgZ+AAPzAPJYCSgqpJIAAJACJSFEBEpAkKBkA8wQglAPEOqkngAAjAIlJygES8CTlZADzA5QCCkqpJAAAIICJSkoBEoAlJRkA8QRkAZE6rjMQAHcAZjnEANJgHOIBZAABlQARCAYAMAAABGAQHwIZAAAQGHkQFwwZAAYCABUg/AhROAgGYBFNAGVwDABjihAZAEIQCAIgGQBXIBAAJEoZAPcAHmIgPcZoDjKgIDzGIEAIMgDYkiARKVQJSqAgESkggBkAQvIgES8ZADjvIQAZANaCIBEoVAlJQCARCCAAZADnOAZjMA0mVAkxQHAQxjEZAAbDAAECAAbIAAEPAAoCAA/6AAIAjREBGQAPTxABXwMfgAD+BBACLx+ANhAHD2gQAi/8f5oQCBQ/LwsIAgAvAf7+EAgPMBEGHw9JEQIf+JQRCAGtEA0CAF3AAAAAfxYAAvgRDwIAr1AAAAAAAA=="
        [uVar1 * 0xc + 0xac] == *(char *)(gp + -0x791)) {
      if ("HwABAJ0vP/8BAABPAAAAARcAAG///8AAAAcZAAJP8AAADxkAAk/4AAAfGQACH/x8AARv//4AAD/gRwEAbwH+AAB/gBkAAF8A/wAAf34AAV/4fwAA/uEAAW/+P4AA/HBLAABvBz+AAPxgGQAAoQOfgAD8x/////wZAQaHAKEBn4AA/N/////+GQEVwDwADxkAPW/P/////AN9AAAGcwAGAgABfQAPGQD/////DiIB/C4EMmDADAkABDMEEwHcBA8ZAAYUAFgEBTIA2YH4fMN8HgHj8Dw+AfAZAMjMxsN2MwBgwAxjAxgZAMn5hsDDY2GAYMAMYAAZAFGBhnDDYBkAODgA+DIA2oGGHMNgfwBgwAwOAbgZAJoGw2BgAGDADANkANiBhsZnYDGAeMAPYwM4MgDI/YZ8P2AfADBwBj4BZAANAgAE4QANAgAPGQD/VlDAAAAAA1MJCiYCDxkAIMl4wPD4eD8AHj8H48H0AcnMwZmMzGcAMzmM5mMmAsmGww2BhsMAYbDYbDajAn+AwwzhhsM+GQACnDn8wwB/MNhv5jIAmA2AwwBgMNhsBhkA2ADG2ZmMxmcAMbDM5jN9ANkAfHDw+Hw/AB8wx+PhrwAMAgAPigL/VgsCAAt3ARUwMwoPGQAWBVEABjIAkgH7DHh8/eDx+BwABhkAnAM7DMzGMGGZzBkAnwYbDYbAMGMNhhkAAR9wGQAEL/wcGQAEL4AGGQABoQM5nMbGMHmZhjhlAAaWAI0B+Px8fBww8RkAAdIFBgIABjIADxkAIAoCAAdLAAoCAA8ZAP//GxE+OwLDYAAKcACACAABEAAEPwIRIBkATCAACiAZAPIcZQGRM04jEAAjgeY5kQPcYBzIgZ+AAPzAPJYCSgqpJIAAJACJSFEBEpAkKBkA8wQglAPEOqkngAAjAIlJygES8CTlZADzA5QCCkqpJAAAIICJSkoBEoAlJRkA8QRkAZE6rjMQAHcAZjnEANJgHOIBZAABlQARCAYAMAAABGAQHwIZAAAQGHkQFwwZAAYCABUg/AhROAgGYBFNAGVwDABjihAZAEIQCAIgGQBXIBAAJEoZAPcAHmIgPcZoDjKgIDzGIEAIMgDYkiARKVQJSqAgESkggBkAQvIgES8ZADjvIQAZANaCIBEoVAlJQCARCCAAZADnOAZjMA0mVAkxQHAQxjEZAAbDAAECAAbIAAEPAAoCAA/6AAIAjREBGQAPTxABXwMfgAD+BBACLx+ANhAHD2gQAi/8f5oQCBQ/LwsIAgAvAf7+EAgPMBEGHw9JEQIf+JQRCAGtEA0CAF3AAAAAfxYAAvgRDwIAr1AAAAAAAA=="
          [uVar1 * 0xc + 0xad] == *(char *)(gp + -0x790)) goto LAB_ram_4201acaa;
    }
  }
  iVar2 = FUN_ram_4201a82e();
  if (iVar2 == -1) {
    iVar2 = 0xff;
  }
  DAT_ram_3fcc5094 = (undefined1)iVar2;
LAB_ram_4201acaa:
  iVar2 = FUN_ram_4201605e();
  if (iVar2 == 0) {
    uVar3 = 0x3c0ad194;
  }
  else {
    uVar3 = 0x3c0ad1a8;
  }
  FUN_ram_4039c61e(0x3fcbb20c,uVar3,0x30);
  FUN_ram_42018dcc();
  return;
}

