
int FUN_ram_4201a82e(void)

{
  int iVar1;
  char *pcVar2;
  
  pcVar2 = 
  "AKEBn4AA/N/////+GQEVwDwADxkAPW/P/////AN9AAAGcwAGAgABfQAPGQD/////DiIB/C4EMmDADAkABDMEEwHcBA8ZAAYUAFgEBTIA2YH4fMN8HgHj8Dw+AfAZAMjMxsN2MwBgwAxjAxgZAMn5hsDDY2GAYMAMYAAZAFGBhnDDYBkAODgA+DIA2oGGHMNgfwBgwAwOAbgZAJoGw2BgAGDADANkANiBhsZnYDGAeMAPYwM4MgDI/YZ8P2AfADBwBj4BZAANAgAE4QANAgAPGQD/VlDAAAAAA1MJCiYCDxkAIMl4wPD4eD8AHj8H48H0AcnMwZmMzGcAMzmM5mMmAsmGww2BhsMAYbDYbDajAn+AwwzhhsM+GQACnDn8wwB/MNhv5jIAmA2AwwBgMNhsBhkA2ADG2ZmMxmcAMbDM5jN9ANkAfHDw+Hw/AB8wx+PhrwAMAgAPigL/VgsCAAt3ARUwMwoPGQAWBVEABjIAkgH7DHh8/eDx+BwABhkAnAM7DMzGMGGZzBkAnwYbDYbAMGMNhhkAAR9wGQAEL/wcGQAEL4AGGQABoQM5nMbGMHmZhjhlAAaWAI0B+Px8fBww8RkAAdIFBgIABjIADxkAIAoCAAdLAAoCAA8ZAP//GxE+OwLDYAAKcACACAABEAAEPwIRIBkATCAACiAZAPIcZQGRM04jEAAjgeY5kQPcYBzIgZ+AAPzAPJYCSgqpJIAAJACJSFEBEpAkKBkA8wQglAPEOqkngAAjAIlJygES8CTlZADzA5QCCkqpJAAAIICJSkoBEoAlJRkA8QRkAZE6rjMQAHcAZjnEANJgHOIBZAABlQARCAYAMAAABGAQHwIZAAAQGHkQFwwZAAYCABUg/AhROAgGYBFNAGVwDABjihAZAEIQCAIgGQBXIBAAJEoZAPcAHmIgPcZoDjKgIDzGIEAIMgDYkiARKVQJSqAgESkggBkAQvIgES8ZADjvIQAZANaCIBEoVAlJQCARCCAAZADnOAZjMA0mVAkxQHAQxjEZAAbDAAECAAbIAAEPAAoCAA/6AAIAjREBGQAPTxABXwMfgAD+BBACLx+ANhAHD2gQAi/8f5oQCBQ/LwsIAgAvAf7+EAgPMBEGHw9JEQIf+JQRCAGtEA0CAF3AAAAAfxYAAvgRDwIAr1AAAAAAAA=="
  ;
  iVar1 = 0;
  while ((pcVar2[8] != *(char *)(gp + -0x791) || (pcVar2[9] != *(char *)(gp + -0x790)))) {
    iVar1 = iVar1 + 1;
    pcVar2 = pcVar2 + 0xc;
    if (iVar1 == 7) {
      return -1;
    }
  }
  return iVar1;
}

