
void FUN_ram_420203ae(void)

{
  FUN_ram_4202015a(0x20,0,0,
                   "AQBvAf4AAH+AGQAAXwD/AAB/fgABX/h/AAD+ZQABb/4/gAD8cEsAAG8HH4AA/GAZAABfAx+AAPyWAAIfnxkA//////+8DPkFBNwFIgP8HAAQMN4HJj/wGQAoB44ZABbgGQAiDgcZAAECACYwABkANhwDgGcACBkA2hgBjPBmAgIDMDwwIEAZAMfP+GYGBwMw/jBwwDFLANg4AM8cZgYDBjHHGHDAfQDnMADODGMGAwYxgxjwwDivAPYAMADMDGMMAYYzAZjRgHAwlgD2ADAAzAxhDAGMM/+YmYAAOBkA9gA4AcwMYYgBjDP/jZmAABgZANgYAYwMYZgAzDMADYkAGQCBHAGMDGCYANgZABdgMgDYDAMMDGDQAFgxgYcPAH0A9gAPDwwMYPAAcDHDBw8AOHBkAOcD/gwMYHAAcDD+BwYAH+EA9gAA8AQEQGAAIDA4AgYAB4AyAAECAAVfAQcsAQECAAi/BwTbAV8AAAAAAxkABgIgAAICAAgyAAkCAA8ZACYIdwACXAIDSwAYw2AACBkAHwMZAB70Ak/B4E4eA8AI4A8GYA8weCAQsQj0As/H8P8/D+Af+D+H4D+w/jAwGQD3AMMOGOHjnDAOHHHHADDxhxkA9QEMHOHBmDAMDGDGAGBxAxhgMgDYDAzAwZwADAzAZgBgcBkA5x/8wIGPAAwO/+YAYDAfMgD1AR/8wIGH4AgG/+YAYDH/DMBLAOcYAMCBgPAMDsAGAGAzgxkA6AwAwIGAMAwMwAYAYHMDGQAxDMCBlgB1ZgBgcwcHgEsA9QEOGMCBnDAOHHDGADDzjweGGQD0Acf4wcGP4Av4P4YAP7H7Aw4ZAPQCQcHgQIEDwAjgDgYADiDzAwQZAAN2ARMICAAVA6kBAxEABBkAHAYZABMcIQAcHhkABDIAByADDQIAAw0CDRgAC5YABwIADzIA//////8LCBMIBAIAAdIPDwQQBQ82EAYPaBAGD5oQBg/MEAYPmRABAf4QDzARBg/kEAEBYhEPlBEGD8YRBg/4EQYPAgCvUAAAAAAA"
                  );
  FUN_ram_4202015a(0x21,0,1,
                   "AAJP8AAADxkAAk/4AAAfGQACT/wAAD8ZAAJf/gAAP8BHAQBvAf4AAH+AGQAAXwD/AAB/fgABX/h/AAD+ZQABb/4/gAD8cEsAAG8HH4AA/GAZAABfAx+AAPyWAAIfnxkA//////+8DPkFBNwFIgP8HAAQMN4HJj/wGQAoB44ZABbgGQAiDgcZAAECACYwABkANhwDgGcACBkA2hgBjPBmAgIDMDwwIEAZAMfP+GYGBwMw/jBwwDFLANg4AM8cZgYDBjHHGHDAfQDnMADODGMGAwYxgxjwwDivAPYAMADMDGMMAYYzAZjRgHAwlgD2ADAAzAxhDAGMM/+YmYAAOBkA9gA4AcwMYYgBjDP/jZmAABgZANgYAYwMYZgAzDMADYkAGQCBHAGMDGCYANgZABdgMgDYDAMMDGDQAFgxgYcPAH0A9gAPDwwMYPAAcDHDBw8AOHBkAOcD/gwMYHAAcDD+BwYAH+EA9gAA8AQEQGAAIDA4AgYAB4AyAAECAAVfAQcsAQECAAi/BwTbAV8AAAAAAxkABgIgAAICAAgyAAkCAA8ZACYIdwACXAIDSwAYw2AACBkAHwMZAB70Ak/B4E4eA8AI4A8GYA8weCAQsQj0As/H8P8/D+Af+D+H4D+w/jAwGQD3AMMOGOHjnDAOHHHHADDxhxkA9QEMHOHBmDAMDGDGAGBxAxhgMgDYDAzAwZwADAzAZgBgcBkA5x/8wIGPAAwO/+YAYDAfMgD1AR/8wIGH4AgG/+YAYDH/DMBLAOcYAMCBgPAMDsAGAGAzgxkA6AwAwIGAMAwMwAYAYHMDGQAxDMCBlgB1ZgBgcwcHgEsA9QEOGMCBnDAOHHDGADDzjweGGQD0Acf4wcGP4Av4P4YAP7H7Aw4ZAPQCQcHgQIEDwAjgDgYADiDzAwQZAAN2ARMICAAVA6kBAxEABBkAHAYZABMcIQAcHhkABDIAByADDQIAAw0CDRgAC5YABwIADzIA//////8LCBMIBAIAAdIPDwQQBQ82EAYPaBAGD5oQBg/MEAYPmRABAf4QDzARBg/kEAEBYhEPlBEGD8YRBg/4EQYPAgCvUAAAAAAA"
                  );
  FUN_ram_4202015a(0x22,0,2,&DAT_ram_3c0f1df0);
  FUN_ram_4202015a(0x23,0,3,&DAT_ram_3c0f1dc4);
  FUN_ram_4202015a(0x24,0,4,&DAT_ram_3c0f1d98);
  DAT_ram_3fcc5147 = 0;
  return;
}

