
void FUN_ram_42020b2e(void)

{
  undefined1 auStack_40 [24];
  undefined1 auStack_28 [32];
  
  FUN_ram_4039c11e(auStack_40,
                   "cEsAAG8HH4AA/GAZAABfAx+AAPyWAAIfnxkA//////+8DPkFBNwFIgP8HAAQMN4HJj/wGQAoB44ZABbgGQAiDgcZAAECACYwABkANhwDgGcACBkA2hgBjPBmAgIDMDwwIEAZAMfP+GYGBwMw/jBwwDFLANg4AM8cZgYDBjHHGHDAfQDnMADODGMGAwYxgxjwwDivAPYAMADMDGMMAYYzAZjRgHAwlgD2ADAAzAxhDAGMM/+YmYAAOBkA9gA4AcwMYYgBjDP/jZmAABgZANgYAYwMYZgAzDMADYkAGQCBHAGMDGCYANgZABdgMgDYDAMMDGDQAFgxgYcPAH0A9gAPDwwMYPAAcDHDBw8AOHBkAOcD/gwMYHAAcDD+BwYAH+EA9gAA8AQEQGAAIDA4AgYAB4AyAAECAAVfAQcsAQECAAi/BwTbAV8AAAAAAxkABgIgAAICAAgyAAkCAA8ZACYIdwACXAIDSwAYw2AACBkAHwMZAB70Ak/B4E4eA8AI4A8GYA8weCAQsQj0As/H8P8/D+Af+D+H4D+w/jAwGQD3AMMOGOHjnDAOHHHHADDxhxkA9QEMHOHBmDAMDGDGAGBxAxhgMgDYDAzAwZwADAzAZgBgcBkA5x/8wIGPAAwO/+YAYDAfMgD1AR/8wIGH4AgG/+YAYDH/DMBLAOcYAMCBgPAMDsAGAGAzgxkA6AwAwIGAMAwMwAYAYHMDGQAxDMCBlgB1ZgBgcwcHgEsA9QEOGMCBnDAOHHDGADDzjweGGQD0Acf4wcGP4Av4P4YAP7H7Aw4ZAPQCQcHgQIEDwAjgDgYADiDzAwQZAAN2ARMICAAVA6kBAxEABBkAHAYZABMcIQAcHhkABDIAByADDQIAAw0CDRgAC5YABwIADzIA//////8LCBMIBAIAAdIPDwQQBQ82EAYPaBAGD5oQBg/MEAYPmRABAf4QDzARBg/kEAEBYhEPlBEGD8YRBg/4EQYPAgCvUAAAAAAA"
                   ,0x18);
  FUN_ram_42048298(auStack_40);
  FUN_ram_4039c11e(auStack_28,
                   "APyWAAIfnxkA//////+8DPkFBNwFIgP8HAAQMN4HJj/wGQAoB44ZABbgGQAiDgcZAAECACYwABkANhwDgGcACBkA2hgBjPBmAgIDMDwwIEAZAMfP+GYGBwMw/jBwwDFLANg4AM8cZgYDBjHHGHDAfQDnMADODGMGAwYxgxjwwDivAPYAMADMDGMMAYYzAZjRgHAwlgD2ADAAzAxhDAGMM/+YmYAAOBkA9gA4AcwMYYgBjDP/jZmAABgZANgYAYwMYZgAzDMADYkAGQCBHAGMDGCYANgZABdgMgDYDAMMDGDQAFgxgYcPAH0A9gAPDwwMYPAAcDHDBw8AOHBkAOcD/gwMYHAAcDD+BwYAH+EA9gAA8AQEQGAAIDA4AgYAB4AyAAECAAVfAQcsAQECAAi/BwTbAV8AAAAAAxkABgIgAAICAAgyAAkCAA8ZACYIdwACXAIDSwAYw2AACBkAHwMZAB70Ak/B4E4eA8AI4A8GYA8weCAQsQj0As/H8P8/D+Af+D+H4D+w/jAwGQD3AMMOGOHjnDAOHHHHADDxhxkA9QEMHOHBmDAMDGDGAGBxAxhgMgDYDAzAwZwADAzAZgBgcBkA5x/8wIGPAAwO/+YAYDAfMgD1AR/8wIGH4AgG/+YAYDH/DMBLAOcYAMCBgPAMDsAGAGAzgxkA6AwAwIGAMAwMwAYAYHMDGQAxDMCBlgB1ZgBgcwcHgEsA9QEOGMCBnDAOHHDGADDzjweGGQD0Acf4wcGP4Av4P4YAP7H7Aw4ZAPQCQcHgQIEDwAjgDgYADiDzAwQZAAN2ARMICAAVA6kBAxEABBkAHAYZABMcIQAcHhkABDIAByADDQIAAw0CDRgAC5YABwIADzIA//////8LCBMIBAIAAdIPDwQQBQ82EAYPaBAGD5oQBg/MEAYPmRABAf4QDzARBg/kEAEBYhEPlBEGD8YRBg/4EQYPAgCvUAAAAAAA"
                  );
  FUN_ram_42048298(auStack_28);
  FUN_ram_42048144(5,1);
  FUN_ram_42048144(6,0);
  FUN_ram_42048144(7,0);
  FUN_ram_42048144(4,1);
  return;
}

