
void FUN_ram_4207cf3a(int *param_1,undefined4 param_2,char *param_3)

{
  byte bVar1;
  int iVar2;
  uint uVar3;
  byte bVar4;
  uint uVar5;
  int iVar6;
  
  iVar2 = FUN_ram_4207940a();
  if (param_1 == (int *)0x0) {
LAB_ram_4207cf5c:
    FUN_ram_4207a038(1,0x800,1,&DAT_ram_3c0fe7c8,&DAT_ram_3c0c426c,0x984);
    do {
                    /* WARNING: Do nothing block with infinite loop */
    } while( true );
  }
  iVar6 = *param_1;
  if (iVar6 == 0) goto LAB_ram_4207cf5c;
  FUN_ram_4207c732(param_1,param_2);
  if ((*(uint *)(iVar6 + 0x134) & 0xc) == 0) goto LAB_ram_4207cfa8;
  uVar5 = param_1[3];
  if ((*(ushort *)(param_1 + 0x57) & 0xc) == 0) {
    uVar5 = uVar5 & 0xffffdfff;
    uVar3 = 0x1000;
LAB_ram_4207cfa4:
    uVar5 = uVar5 | uVar3;
  }
  else {
    if ((*(ushort *)(param_1 + 0x57) & 0xc) == 4) {
      uVar3 = 0x3000;
      goto LAB_ram_4207cfa4;
    }
    uVar5 = uVar5 & 0xffffcfff;
  }
  param_1[3] = uVar5;
LAB_ram_4207cfa8:
  if (*param_3 == -0x23) {
    param_3 = param_3 + 4;
  }
  *(char *)((int)param_1 + 0x15f) = param_3[2];
  bVar1 = param_3[3];
  *(byte *)(param_1 + 0x58) = bVar1 & 3;
  *(byte *)((int)param_1 + 0x161) = param_3[4] & 3;
  *(byte *)((int)param_1 + 0x162) = param_3[6] & 0x7f;
  bVar4 = bVar1 & 4;
  if ((((bVar1 & 4) != 0) && (bVar4 = 0, (*(uint *)(iVar6 + 300) & 0x1000000) != 0)) &&
     (bVar4 = 1, (bVar1 & 3) != 1)) {
    bVar4 = ((bVar1 & 3) == 3) << 1;
  }
  if (((bVar1 & 8) == 0) || ((*(uint *)(iVar6 + 300) & 0x20000000) == 0)) {
    uVar5 = param_1[3] & 0xffffbfffU | 0xc0;
  }
  else {
    uVar5 = param_1[3] | 0x40c0;
  }
  param_1[3] = uVar5;
  if (*(byte *)(param_1 + 0x2b) != bVar4) {
    *(byte *)(param_1 + 0x2b) = bVar4;
    if (*(int **)(iVar6 + 0xe4) == param_1) {
      FUN_ram_4207a038(1,8,5,
                       "AgABhQASvzIAAhsABS4BOKv/+jMFBQIAE+plAAWCAAcyAAUlAAkCAAEhAALsAgIYAH/qqqr+qq//UQMDALkFAZcAMq///48BAZ8AAV0AARUADwIAAwHmAATBAQ8yABIBTgElr/5UAAVkAAHDAg8CAAEBlwAlqr4yAAMJAA8yAAgDEgQDKQAPMgASAS4BAuwCBjIAH/5kAAkClwAFIgACbQAPMgAKAvwABzIAEr9aBA/6AAYFlwADIgACCQAPZAALA/wAA0AFDzIAEgL8AAHrAQ8yABQDZQAClwACCAAPlgAMCWUAAjIABAcADwIABgIvAQHKAAMrAAMHAA8CAAYDlAEWv10AA0AADwIABgMyABWqMgAGmgIPAgAEAskAA90DAmoACYEIDgIABTIAA5MCAwcADwIACAL6AAoCAAOgAQ8CAARK6qqqujAADzIADTSqqqr9AAUCAA9kAAs0qqqqwwIGAgAPkAAEAgIAMaqqqzsHCQIAAhsADwIAAwJKBAkxAQaVAw8CAAIDsAELMgECmgIPAgADAzIAA8QCAQIABBMADwIABAUfAAVmAALbAA8vAAQC7gIEgwAC0wABcAAPMgAUBaMFD1sKAwQCAAWhBgoyAAR4AA8CAAAPMgABARkHH/4tAAABAgAIggAESwMBfQcNyggEAgAKMgAC8gABBgcU6iIADAIADzIAAV3/qqqqv/wIBAIADzIAAgGcAQQiAAwCAANmBgECAASWAAKTBAETAA8CAAAFJgABjQARqwgADzIAIAFjAwI9AA4CAAVYAAEcBgNkAAGYAgETAA8CAAAKMgAEIQES6sEEDwIAAg8yAAMBkgEPMAACDzIABQHQCg8yAAYBpQUBAgAFBQkBKwQBEwAPAgAACDIABpYCH6rIAAoGZAAFMgAPXgEMCTIAAg0AAVsED5EAAAMACQIlAAkNAAEhBAIUAA0CAAUZBAMyAAHDAQGVAA8sAQUPMgACAbsCDzIAEgOcCQFjAA8gAwYJZAAS/1oAAvgAD4QDBgj6ABH/cgUBYwAP6AMICTIAAfUBAcYAAUwEcv1VVVVX1X8XAVL//1VVW1gCNK///xYAQeqqqq+UAAIQEA0yABJVWgcHMgAh5WqKAQLPAA8yAAERX7sAFqtkABTVMgAC1gFU/qqVaquAAG///1WqlVsyAAYERQUl1X9OAG///1X/9VcyAAUUq+0A8RTVf//VflW//+VW////Vf/5V/+VW6qqlVb/1X/5W/5Vb/1VVcUABjQI9RHVf//VdVVv/1VVf///Vf/9V/1VVWqpVVV/1X/lX/VVVjIABGMAkf/Vf//VVVVb/fQA8wVV//1X9VVVWqVVVV/Vf5V/1VVV+WQAAvgAAJQRstV//9VW5Vf1W/lXlgDyAtVb5VqlVuVb1X9V/1V/lWqVLAECLgAEMgBhX/lX9V/9MgD0AfVX1X/1VpVa/VfVfVb/Vf8yAAQpAQOWAHJ//Vflb/5WXgHxAZV//VaVar1X1WVb/laqpVpkAAaUAAKWAPENf/1X5VVVVv//VVVVb5W//VaVaqqq1VVv6VVVVTIABVoBBzIAFNUyACO/VTIAT5VVWqkyABEkW/9kADWVVVYyAAl8AwH0AUL9V+Vv9AEZ/zIAQVaqqqrIAAKQAAICAAYyABOrMgDBf/lWlVqpVpVpVapVMgAGrQUBAgADMgAx9V/+XgHxBf//1W/1WpVapVaValVqVaqVapVvVAMBLQABAgADMgAz+ValMgBR5VZVXqUkAYWValVVVWqVWhcFAgIAAzIABCYCcv//+VVVf6kyAHFalVVVquVV/QcCLgAHXgEi/5WKAvwE///+VVX/6lVVqpVqpValVVb/9TIABAIAFf6mAWL6r///6VrjAlWVv///qgAJDwIACgIMBAJGAA8yABMy////PAQCXAQJwwEPAgAQBHoEDwIAFwuRAQ8CABABoBEPKAAQBgIACZEBVoAAAAC/HAACAgAb+BMAAY4JAhsAAjIAFAsNAAQCAAwyAAn8B1SAAAAAAioABAIACDIAIfQA8wQGawEvgACX..." /* TRUNCATED STRING LITERAL */
                      );
      *(byte *)(iVar6 + 299) = bVar4;
      FUN_ram_4207c908((int)param_1 + 0xab);
      FUN_ram_420879c4(1,param_1);
    }
  }
  if ((*(byte *)(iVar2 + 1) != bVar4) && (bVar4 != 0)) {
    FUN_ram_4207a038(1,8,5,
                     "BS4BOKv/+jMFBQIAE+plAAWCAAcyAAUlAAkCAAEhAALsAgIYAH/qqqr+qq//UQMDALkFAZcAMq///48BAZ8AAV0AARUADwIAAwHmAATBAQ8yABIBTgElr/5UAAVkAAHDAg8CAAEBlwAlqr4yAAMJAA8yAAgDEgQDKQAPMgASAS4BAuwCBjIAH/5kAAkClwAFIgACbQAPMgAKAvwABzIAEr9aBA/6AAYFlwADIgACCQAPZAALA/wAA0AFDzIAEgL8AAHrAQ8yABQDZQAClwACCAAPlgAMCWUAAjIABAcADwIABgIvAQHKAAMrAAMHAA8CAAYDlAEWv10AA0AADwIABgMyABWqMgAGmgIPAgAEAskAA90DAmoACYEIDgIABTIAA5MCAwcADwIACAL6AAoCAAOgAQ8CAARK6qqqujAADzIADTSqqqr9AAUCAA9kAAs0qqqqwwIGAgAPkAAEAgIAMaqqqzsHCQIAAhsADwIAAwJKBAkxAQaVAw8CAAIDsAELMgECmgIPAgADAzIAA8QCAQIABBMADwIABAUfAAVmAALbAA8vAAQC7gIEgwAC0wABcAAPMgAUBaMFD1sKAwQCAAWhBgoyAAR4AA8CAAAPMgABARkHH/4tAAABAgAIggAESwMBfQcNyggEAgAKMgAC8gABBgcU6iIADAIADzIAAV3/qqqqv/wIBAIADzIAAgGcAQQiAAwCAANmBgECAASWAAKTBAETAA8CAAAFJgABjQARqwgADzIAIAFjAwI9AA4CAAVYAAEcBgNkAAGYAgETAA8CAAAKMgAEIQES6sEEDwIAAg8yAAMBkgEPMAACDzIABQHQCg8yAAYBpQUBAgAFBQkBKwQBEwAPAgAACDIABpYCH6rIAAoGZAAFMgAPXgEMCTIAAg0AAVsED5EAAAMACQIlAAkNAAEhBAIUAA0CAAUZBAMyAAHDAQGVAA8sAQUPMgACAbsCDzIAEgOcCQFjAA8gAwYJZAAS/1oAAvgAD4QDBgj6ABH/cgUBYwAP6AMICTIAAfUBAcYAAUwEcv1VVVVX1X8XAVL//1VVW1gCNK///xYAQeqqqq+UAAIQEA0yABJVWgcHMgAh5WqKAQLPAA8yAAERX7sAFqtkABTVMgAC1gFU/qqVaquAAG///1WqlVsyAAYERQUl1X9OAG///1X/9VcyAAUUq+0A8RTVf//VflW//+VW////Vf/5V/+VW6qqlVb/1X/5W/5Vb/1VVcUABjQI9RHVf//VdVVv/1VVf///Vf/9V/1VVWqpVVV/1X/lX/VVVjIABGMAkf/Vf//VVVVb/fQA8wVV//1X9VVVWqVVVV/Vf5V/1VVV+WQAAvgAAJQRstV//9VW5Vf1W/lXlgDyAtVb5VqlVuVb1X9V/1V/lWqVLAECLgAEMgBhX/lX9V/9MgD0AfVX1X/1VpVa/VfVfVb/Vf8yAAQpAQOWAHJ//Vflb/5WXgHxAZV//VaVar1X1WVb/laqpVpkAAaUAAKWAPENf/1X5VVVVv//VVVVb5W//VaVaqqq1VVv6VVVVTIABVoBBzIAFNUyACO/VTIAT5VVWqkyABEkW/9kADWVVVYyAAl8AwH0AUL9V+Vv9AEZ/zIAQVaqqqrIAAKQAAICAAYyABOrMgDBf/lWlVqpVpVpVapVMgAGrQUBAgADMgAx9V/+XgHxBf//1W/1WpVapVaValVqVaqVapVvVAMBLQABAgADMgAz+ValMgBR5VZVXqUkAYWValVVVWqVWhcFAgIAAzIABCYCcv//+VVVf6kyAHFalVVVquVV/QcCLgAHXgEi/5WKAvwE///+VVX/6lVVqpVqpValVVb/9TIABAIAFf6mAWL6r///6VrjAlWVv///qgAJDwIACgIMBAJGAA8yABMy////PAQCXAQJwwEPAgAQBHoEDwIAFwuRAQ8CABABoBEPKAAQBgIACZEBVoAAAAC/HAACAgAb+BMAAY4JAhsAAjIAFAsNAAQCAAwyAAn8B1SAAAAAAioABAIACDIAIfQA8wQGawEvgACXAAAPMgALVAKqQAA/..." /* TRUNCATED STRING LITERAL */
                    );
    return;
  }
  return;
}

