
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 thunk_FUN_ram_42094404(void)

{
  uint uVar1;
  
  uVar1 = 0;
  FUN_ram_4207a038(6,1,3,
                   "MgAEHwAPMgADROqqqq8iAFf///+qqnQAFuo9AAcCABrqegAn6qpCAA8yAAMHtwAA4gAY+hAADzIABgIsAAICAA8yABMEGwEPZAAUD8gAHw8sAR8PkAEfCjIAD/QBERn+LQER6vQBBNMBFvoLAAgCAAiBAQHzAQb1AQqAAAUCAAjlAVb/qqqqrkMACoAABQIAFupUAGb//qqqqr5DABb+PQAIAgAX+skAAQwAFqoRAAGXAhj6LgAM5gEBuQAGjQIC/AISqigABgIAFv6GAALPAQFiAQE6AgE5AQhLAQMCAAF7AAIMAAIzAgEpABG/DgABAgACHAAHAgAW6nkAAuoAApUBBgIABywAAgIABuECA04BAZcABwIAAicABwIABskAEv5pAQPxAAUCAAcsAAICABX+yQABKwEd/5cAAicACAIABXEEBEgCC2UACCwAAgIABYEBBW4EBvwABxcBBwIAFPqXAAJdAQMSAAECABOrDQELAgABhQASvzIAAhsABS4BOKv/+jMFBQIAE+plAAWCAAcyAAUlAAkCAAEhAALsAgIYAH/qqqr+qq//UQMDALkFAZcAMq///48BAZ8AAV0AARUADwIAAwHmAATBAQ8yABIBTgElr/5UAAVkAAHDAg8CAAEBlwAlqr4yAAMJAA8yAAgDEgQDKQAPMgASAS4BAuwCBjIAH/5kAAkClwAFIgACbQAPMgAKAvwABzIAEr9aBA/6AAYFlwADIgACCQAPZAALA/wAA0AFDzIAEgL8AAHrAQ8yABQDZQAClwACCAAPlgAMCWUAAjIABAcADwIABgIvAQHKAAMrAAMHAA8CAAYDlAEWv10AA0AADwIABgMyABWqMgAGmgIPAgAEAskAA90DAmoACYEIDgIABTIAA5MCAwcADwIACAL6AAoCAAOgAQ8CAARK6qqqujAADzIADTSqqqr9AAUCAA9kAAs0qqqqwwIGAgAPkAAEAgIAMaqqqzsHCQIAAhsADwIAAwJKBAkxAQaVAw8CAAIDsAELMgECmgIPAgADAzIAA8QCAQIABBMADwIABAUfAAVmAALbAA8vAAQC7gIEgwAC0wABcAAPMgAUBaMFD1sKAwQCAAWhBgoyAAR4AA8CAAAPMgABARkHH/4tAAABAgAIggAESwMBfQcNyggEAgAKMgAC8gABBgcU6iIADAIADzIAAV3/qqqqv/wIBAIADzIAAgGcAQQiAAwCAANmBgECAASWAAKTBAETAA8CAAAFJgABjQARqwgADzIAIAFjAwI9AA4CAAVYAAEcBgNkAAGYAgETAA8CAAAKMgAEIQES6sEEDwIAAg8yAAMBkgEPMAACDzIABQHQCg8yAAYBpQUBAgAFBQkBKwQBEwAPAgAACDIABpYCH6rIAAoGZAAFMgAPXgEMCTIAAg0AAVsED5EAAAMACQIlAAkNAAEhBAIUAA0CAAUZBAMyAAHDAQGVAA8sAQUPMgACAbsCDzIAEgOcCQFjAA8gAwYJZAAS/1oAAvgAD4QDBgj6ABH/cgUBYwAP6AMICTIAAfUBAcYAAUwEcv1VVVVX1X8XAVL//1VVW1gCNK///xYAQeqqqq+UAAIQEA0yABJVWgcHMgAh5WqKAQLPAA8yAAERX7sAFqtkABTVMgAC1gFU/qqVaquAAG///1WqlVsyAAYERQUl1X9OAG///1X/9VcyAAUUq+0A8RTVf//VflW//+VW////Vf/5V/+VW6qqlVb/1X/5W/5Vb/1VVcUABjQI9RHVf//VdVVv/1VVf///Vf/9V/1VVWqpVVV/1X/lX/VVVjIABGMAkf/Vf//VVVVb/fQA8wVV//1X9VVVWqVVVV/Vf5V/1VVV+WQAAvgAAJQRstV//9VW5Vf1W/lXlgDyAtVb5VqlVuVb1X9V/1V/lWqVLAECLgAEMgBhX/lX9V/9MgD0AfVX1X/1VpVa/VfVfVb/Vf8yAAQpAQOWAHJ//Vflb/5WXgHxAZV//VaVar1X1WVb/laqpVpkAAaUAAKWAPENf/1X5VVVVv//VVVVb5W//VaVaqqq1VVv6VVV..." /* TRUNCATED STRING LITERAL */
                  );
  do {
    if (*(char *)(_DAT_ram_3ff4fbbc + uVar1 * 0x28 + 0x12) != '\0') {
      FUN_ram_4207a038(6,0x40,2,&DAT_ram_3c10230c,uVar1);
      FUN_ram_420942e8(uVar1 & 0xff);
    }
    uVar1 = uVar1 + 1;
  } while (uVar1 != 5);
  return 0;
}

